SMLibrary.Presentation/Controllers/IdentityController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SMLibrary.Presentation.Dtos;
using SMlibraryApp.Core.Repository;
using SMlibraryApp.Presentation.Dtos;

namespace SMlibraryApp.Presentation.Controllers;
public class IdentityController : Controller
{
    private readonly IUserRepository userRepository;
    private readonly UserManager<IdentityUser> UserManager;
    private readonly SignInManager<IdentityUser> signInManager;
    private readonly RoleManager<IdentityRole> roleManager;
    public IdentityController(IUserRepository userRepository, 
    UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager,
    RoleManager<IdentityRole> roleManager)
    {
        this.signInManager = signInManager;
        this.roleManager = roleManager;
        this.UserManager = userManager;
        this.userRepository = userRepository;
    }
    [HttpGet]
    [AllowAnonymous]
    public async Task<IActionResult> Login(string? returnUrl)
    {
        base.ViewData["returnUrl"] = returnUrl;

        return base.View();
    }

    [HttpGet]
    [AllowAnonymous]
    public async Task<IActionResult> Register()
    {
        return base.View();
    }

    [HttpPost]
    [AllowAnonymous]
    public async Task<IActionResult> Login([FromForm] LoginDto loginDto)
    {
        var result = await signInManager.PasswordSignInAsync(loginDto.UserName, loginDto.Password, false, false);
        if (result.Succeeded)
        {
            return RedirectToAction("Get", "Books");
        }
        return View();
    }

    [HttpPost]
    [AllowAnonymous]
    public async Task<IActionResult> Register([FromForm] RegisterDto registerDto)
    {
        var newUser = new IdentityUser
        {
            UserName = registerDto.UserName,
        };
        var result = await this.UserManager.CreateAsync(newUser, registerDto.Password);
        if (result is null)
        {
            return BadRequest(result);
        }
         if(registerDto.UserName.Contains("admin")) {
            var role = new IdentityRole {Name = "Admin"};
            await roleManager.CreateAsync(role);

            await UserManager.AddToRoleAsync(newUser, role.Name);
        }

        return RedirectToAction("Login");
    }

    [HttpGet]
    [Authorize]
    public async Task<IActionResult> LogOut()
    {
        await this.signInManager.SignOutAsync();
        return base.RedirectToAction(actionName: "Index", controllerName: "Home");
    }

    [HttpPost]
    [AllowAnonymous]
    public async Task<IActionResult> ChangePassword([FromForm] PassChangeDto changeDto)
    {
        var user = await userRepository.FindUser(changeDto.Username);
        if(user is null){
            return BadRequest("Incorrect username");
        }
        var check = await UserManager.CheckPasswordAsync(user,changeDto.oldPassword);
        if(check is false){
            return base.BadRequest("Incorrect password");
        }
        var newUser = await UserManager.ChangePasswordAsync(user,changeDto.oldPassword,changeDto.newPassword);
        return RedirectToAction("Login");
    }

    [HttpGet]
    [AllowAnonymous]
    public async Task<IActionResult> ChangePassword()
    {
        return base.View();
    }
    [HttpGet]
    [Authorize(Roles = "Admin")]
    [Route("[action]")]
    public async Task<IActionResult> GetUsers()
    {
        var users =  userRepository.GetUsers();
        return base.View(users);
    }
}

SMLibrary.Presentation/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SMlibraryApp.Core.Repository;

namespace SMLibrary.Presentation.Controllers;


public class UserController : Controller
{
    private readonly IUserRepository userBooksRepository;
    public UserController(IUserRepository userBooksRepository)
    {
        this.userBooksRepository = userBooksRepository;
    }
    [HttpGet]
    [Authorize]
    [Route("/[controller]/Books")]
    public async Task<IActionResult> GetUserItems()
    {
        var userLogin = User.Identity.Name;
        var books = await userBooksRepository.GetBooksbyUser(userLogin);
        return base.View(books);
    }

    [HttpGet]
    [Authorize]
    public async Task<IActionResult> Account()
    {
        return base.View();
    }


    [HttpPost]
    [Authorize]
    [Route("[controller]/add/{id}")]
    public async Task<IActionResult> AddBookToUser(int id)
    {
        var userLogin = User.Identity.Name;
        if (userLogin is null)
            return BadRequest();
        await userBooksRepository.AddBookToUser(id, userLogin);

        return base.RedirectToAction("Get", "Books");
    }

}

SMLibrary.Presentation/Views/Shared/_Layout.cshtml
@{
    bool isAuth = base.User.Identity.IsAuthenticated;
    bool IsAdmin = User.IsInRole("Admin");
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SMlibraryApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SMlibraryApp.styles.css" asp-append-version="true" />
</head>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Library</a>
        <button class=" navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="navbar-nav">
                <a class="nav-item nav-link active" asp-controller="Home" asp-action="Index">Home</a>
                @if (!isAuth)
                {
                    <a class="nav-item nav-link" asp-action="Login" asp-controller="Identity">SingIn/SingUp</a>
                }
                <a class="nav-item nav-link" asp-controller="Books" asp-action="Get">Books</a>
                @if(IsAdmin){
                    <a class="nav-item nav-link" asp-controller="Identity" asp-action="GetUsers">Users</a>
                }
                @if (isAuth)
                {
                    <a class="nav-item nav-link" asp-controller="User" asp-action="Account">Account</a>
                    <a class="nav-item nav-link" asp-controller="Identity" asp-action="LogOut">Log Out</a>
                }
            </div>
        </div>
    </nav>
</header>

<body class="backImage">
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>

    @* без этих скриптов navbar-toggler открывается и сразу закрывается *@
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - SMlibraryApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

</html>